move gpg-plugin to custom profile (#6, #7)
CrumbleWorks/CrumbUtil pull request #9
Opened 2022-08-20 23:34 UTC by McDonnough

- move gpg-plugin to custom profile `package-artifact`
- add profile to maven command in `maven-publish`-action
- move version of gpg-plugin to properties-section

2022-08-21 13:26 UTC, dotSp0T requested changes
oh ffs, kackgithub macht alles uf de glich button, obv gsehni de nid bim sueche bis i es tutorial duregschaffet ha -.-

siehe kommentar im code

2022-08-21 13:26 UTC, dotSp0T commented on pom.xml
> +	<profiles>
Iirückige sind weird?

2022-08-26 19:04 UTC, McDonnough commented on pom.xml
> +	<profiles>
Sött gflickt si.

2022-08-27 08:33 UTC, dotSp0T approved these changes

2022-08-27 08:33 UTC, merged